# Generated by Django 4.0.6 on 2022-07-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoportal', '0002_video_id_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id_commentator',
        ),
    ]
